### PR TITLE
Add hotkey and fix big image Network error issue

### LINKED ISSUE #3: Its get "Network Error" when image is too big.
Issue recurrence:

- Upload a `2.7 MB` jpg
- Do some labels
- Download `json` file, show up `Failed - Network Error`

image

### PR DESCRIPTION
**Pull request by pftom**
I have done two thing in one PR, I'm so sorry 😅 Close #3

### CODE REVIEW

**Review by mrcfps — APPROVED** [review]
Handsome job!

**Comment by mrcfps** [comment]
Now #3 is resolved.

**Comment by pftom** [comment]
Close #3

**Comment by pftom** [comment]
@mRcfps  Do we have other jobs to do in this PR?

**Pull request merged**
